language: node_js
node_js:
  - "14"
dist: trusty
env:
  - NODE_ENV=ci
  - PORT=3000
services:
  - mongodb
  - redis-server
cache:
  directories:
    - node_modules
    - /client/node_modules
install:
  - "npm i"
  - "npm run build"
scripts:
  - nohub npm run start &
  - sleep 3
  - npm run test